services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    restart: unless-stopped
    command:
      - start-dev
      - --import-realm
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: ${KEYCLOAK_DB_URL}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak:/opt/keycloak/data/import:ro
      - ./keycloak/themes:/opt/keycloak/themes:ro
    ports:
      - "8081:8080"

volumes:
  keycloak_data:
