DO $$
BEGIN
    ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PENDING';
    ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PAYMENT_CONFIRMING';
END $$;

ALTER TABLE orders
    ALTER COLUMN status SET DEFAULT 'PENDING';

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS shipping_method VARCHAR(50),
    ADD COLUMN IF NOT EXISTS shipping_price NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50);
