ALTER TABLE products
    ADD COLUMN IF NOT EXISTS removal_reason VARCHAR(40),
    ADD COLUMN IF NOT EXISTS removal_note VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS removed_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE;

UPDATE products
SET expires_at = COALESCE(expires_at, created_at + INTERVAL '45 days')
WHERE expires_at IS NULL;

ALTER TABLE products
    ALTER COLUMN expires_at SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_products_removed_at ON products(removed_at);

CREATE INDEX IF NOT EXISTS idx_products_public_active_approved_name
    ON products(expires_at, name)
    WHERE active = TRUE AND removed_at IS NULL AND moderation_status = 'APPROVED';

CREATE INDEX IF NOT EXISTS idx_products_vendor_visible
    ON products(vendor_id, removed_at, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_products_admin_moderation_created
    ON products(moderation_status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_products_expiration_worker
    ON products(expires_at)
    WHERE active = TRUE AND removed_at IS NULL;

CREATE TABLE IF NOT EXISTS product_removal_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    reason VARCHAR(40) NOT NULL,
    note VARCHAR(1000),
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_product_removal_events_product
    ON product_removal_events(product_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_product_removal_events_occurred
    ON product_removal_events(occurred_at DESC);
