spring:
  datasource:
    url: jdbc:postgresql://db:5432/appdb
    username: appuser
    password: apppass

  application:
    name: localys-marketplace
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

app:
  media:
    upload-dir: uploads
